### CNN visualization 
---

- CNN is a black box 
- 



### Embedding feature anlaysis 2 
---
- Dimensionality reduction 
- t-distributed stochastic neighbor embedding (t-SNE)

- gradient ascent -image synthesis 

1. get a prediction score(of the target class) of a dummy image(blank or random initial)
2. Backpropagate the gradient maximizing the target class score w.r.t the input image 
3. update the current image 

### Saliency test 1
---
- occlusion map -> 각각의 위치를 test해본다 , prediction scores change accoring to the location of mask 

- heatmap representation을 통해서 -> prediction scores drop drastically around the sailent parts ( 히트맵을 통해 어떤 곳이 중요한 keypoint 인지 알 수 있다. )

### Saliency test2 
---

- via backpropagation 

1. get a calss of the target source image 
2. Backpropagate the gradient of the class score w.r.t input domain 
3. Visualize the obtained gradient magnitude map (optionally ,can be accumulated)

#### Recticied unit(backward pass)
- forward Pass 
- saliency amp 
- Deconvolution 
- 
#### Class activation mapping
---

class activation mapping (CAM)
- By visualizing (CAM) , we can interpret why the network classifed the input to that class 
- GAP layer enables localization without supervision 

1. Grad_CAM-> 개발 
2. Get the CAM result without modigying and re_training the original network


In [11]:
import torch
import numpy as np

x = torch.randn(2, requires_grad=True)
y = x * 3
print(y)
gradients = torch.tensor([100, 0.1], dtype=torch.float)
y.backward(gradients)
print(x.grad)
print(y.grad_fn)


tensor([-2.9950, -1.6064], grad_fn=<MulBackward0>)
tensor([300.0000,   0.3000])


In [17]:
import torch.autograd.variable
import warnings
warnings.filterwarnings('ignore')
x = torch.randn(3)
print(x)
x = torch.autograd.variable(x, requires_grad=True)

y = x * 2
print(y)
while y.data.norm() < 1000:
  y = y * 2
  print(y)
print(y)

tensor([ 0.1846,  0.1836, -0.1686])
tensor([ 0.3693,  0.3671, -0.3371], grad_fn=<MulBackward0>)
tensor([ 0.7385,  0.7343, -0.6743], grad_fn=<MulBackward0>)
tensor([ 1.4771,  1.4685, -1.3486], grad_fn=<MulBackward0>)
tensor([ 2.9541,  2.9371, -2.6971], grad_fn=<MulBackward0>)
tensor([ 5.9082,  5.8742, -5.3942], grad_fn=<MulBackward0>)
tensor([ 11.8165,  11.7483, -10.7884], grad_fn=<MulBackward0>)
tensor([ 23.6329,  23.4966, -21.5768], grad_fn=<MulBackward0>)
tensor([ 47.2658,  46.9933, -43.1537], grad_fn=<MulBackward0>)
tensor([ 94.5317,  93.9865, -86.3074], grad_fn=<MulBackward0>)
tensor([ 189.0634,  187.9730, -172.6147], grad_fn=<MulBackward0>)
tensor([ 378.1268,  375.9460, -345.2295], grad_fn=<MulBackward0>)
tensor([ 756.2535,  751.8920, -690.4590], grad_fn=<MulBackward0>)
tensor([ 756.2535,  751.8920, -690.4590], grad_fn=<MulBackward0>)


In [ ]:
from os import path
import wheel
import torch
import torch.nn as nn
import torchvision
from torch.autograd import Variable, Function
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
import functools
import urllib
import numpy as np
import os
import sys
import math
import random
import matplotlib.pyplot as plt
from glob import glob
from scipy.ndimage.filters import gaussian_filter
from IPython.display import clear_output, Image, display, HTML
from google.protobuf import text_format
from io import StringIO
import PIL.Image
% matplotlib inline
plt.rcParams['figure.figsize'] = (10, 10)
plt.rcParams['image.interpolation'] = 'nearest'
