numpy 를 사용하는 이유?
---
- fixed type 
- faster to read less bytes of memory
- no type checking when iterating through objects

    `예를들어 list 의 경우에는 각 배열의 주소들이 연속적이지 않은 경우가 있는데 이는 메모리 블록이 연속적이지 않다는 것을 뜻하며 search 하는데 시간이 걸린다는 것을 의미합니다
    하지만 numpy 의 경우 연속적인 메모리 블록에 저자되기 때문에 빠르게 찾을 수 있습니다.`
---

- numpy
 *benefits*
 1. SIMD Vector processing
 2. Effective Cache Utilization 

In [1]:
import numpy as np
a=np.array([i for i in range(10)])
b=np.array([[i for i in range(10)]for _ in range(5)])
print(a,b)
print(a.ndim,b.ndim)
print(a.shape,b.shape)
print(a.dtype,b.dtype)


[0 1 2 3 4 5 6 7 8 9] [[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
1 2
(10,) (5, 10)
int32 int32


In [10]:
# get a specific elemnet[r,c]
b[1,2]
print(b[:,5])
# getting a little more fancy [start:end:step]
b[0,2:-1:2]

[5 5 5 5 5]


array([2, 4, 6, 8])

In [23]:
# 3dimention 
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b.ndim
b.shape

(2, 2, 2)

In [30]:
np.zeros((2,3,2,3))
np.ones((4,2,2),dtype='int32')
# any other number 
a=np.full((2,2),99)
a.dtype

dtype('int32')

In [34]:
#any other number (full like)

np.full_like(a.reshape(1,4),4)

array([[4, 4, 4, 4]])

In [38]:
# Random decimal numbers
np.random.random_sample(a.shape)

array([[0.45855371, 0.24988252],
       [0.24262309, 0.30486942]])

In [41]:
# Random Interger values

np.random.randint(7,size=(3,3))

array([[0, 2, 0],
       [5, 6, 6],
       [3, 4, 0]])

In [42]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
arr= np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [54]:
output= np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [56]:
# Be careful when copying arrays!!!
a=np.array([1,2,3])
b=a.copy()
b

array([1, 2, 3])

In [61]:
# reorganizing arrays

before= np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((4,2))
after

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [65]:
#vertically stacking vectors

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.stack([v1,v2],axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [73]:
import os 
path='./data'
filepath= os.path.join(path,'text.txt')
Data=open(filepath,'w',)

if os.path.isfile(filepath):
    Data.write(
        '1,13,21,11,196,23,34,45,6,76,74''\n'
        '3,42,12,23,42,43,34,45,45,23,23''\n'
        '10,213,4,2,234,23,435,23,6,547,568'
    )
Data.close()

In [78]:
filedata=np.genfromtxt('./data/text.txt',delimiter=',')
filedata>50
# boolean masking and Advanced indexing
filedata[filedata>50]

array([196.,  76.,  74., 213., 234., 435., 547., 568.])

In [79]:
# any, all의 차이점은 어떤 행이나 열을 기준으로 any는 or을 뜻하고 all은 &&연산을 뜻한다 !!

np.any(filedata>50, axis=0)

array([False,  True, False, False,  True, False,  True, False, False,
        True,  True])

In [100]:
output=np.array([[i+j for i in range(5)]for j in list(range(1,31,5))  ])
print(output)
data=ouput[2:4,:2]
data

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[11, 12],
       [16, 17]])