In [5]:
import numpy as np
n=5000
step=1000
draws=np.random.randint(0,2,(n,step))
steps=np.where(draws>0,1,-1)
walks=steps.cumsum(1)
print(walks)
print(walks.max())
print(walks.min())
print(walks.argmin())
print(walks.argmax())

[[  1   2   3 ... -64 -63 -62]
 [  1   2   1 ...  40  39  38]
 [ -1   0   1 ... -52 -51 -52]
 ...
 [ -1   0  -1 ... -28 -29 -30]
 [ -1  -2  -1 ...   8   7   8]
 [  1   2   1 ... -14 -15 -14]]
119
-132
2573887
2953994


In [8]:
hit30=(np.abs(walks)>=30).any(axis=1)
hit30.sum()

3401