In [130]:
new_img_dir='./input/data/train/new_img'
img_path='./input/data/train/images'
cnt=0
for paths in os.listdir(img_path):
    if paths[0]=='.':continue
    sub_dir=os.path.join(img_path,paths)
    
    for imgs in os.listdir(sub_dir):
        if imgs[0]=='.':continue
        img_dir=os.path.join(sub_dir,imgs)
        image=cv2.imread(img_dir)
        image=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
        boxes,probs= mtcnn.detect(image)
        if len(probs)>1: 
            print(boxes)
        if not isinstance(boxes,np.ndarray):
            print('oh no')
            image=image[100:400,50:350,:]
        else:
            xmin=int(boxes[0,0])-20
            ymin=int(boxes[0,1])-30
            xmax=int(boxes[0,2])+20
            ymax=int(boxes[0,3])+30
            if xmin<0:xmin=0
            if ymin<0:ymin=0
            if xmax>384:xmax=384
            if ymax>512:ymax=512
            image=image[ymin:ymax,xmin:xmax,:]
#         temp=os.path.join(new_img_dir,paths)
#         cnt+=1
#         plt.imsave(os.path.join(temp,imgs),image)
cnt

[[116.46009 143.25746 258.68982 323.38068]
 [298.3283  381.15186 348.59985 442.44498]]
[[128.24576 143.95583 260.71985 308.154  ]
 [306.3845  377.55005 351.59357 432.63675]]
[[119.37738 133.53835 271.2781  335.54495]
 [301.08646 387.86496 358.33392 454.4481 ]]
[[120.03318 145.26224 249.566   308.2451 ]
 [259.71332 147.11377 287.30814 188.65877]]
[[103.024765  83.52531  280.4522   308.8779  ]
 [301.29813  222.08195  342.40518  275.55136 ]]
oh no
oh no
oh no
oh no
oh no
oh no
[[107.36732 250.49338 295.37247 428.65405]
 [117.61358 158.79984 252.69638 325.37753]]
[[ 96.39789   74.22068  281.19168  310.6685  ]
 [ 55.928596 174.34508   70.09641  191.93776 ]]


KeyboardInterrupt: 

In [ ]:

import torch 
import torch.nn as nn 
import torch.optim as optim 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from torchvision import transforms 
import time, os, sys, copy, random 
from efficientnet_pytorch import EfficientNet
from sklearn.model_selection import train_test_split
from glob import glob 
from torch.utils.data import Dataset,DataLoader 
import cv2
import albumentations as A
from facenet_pytorch import MTCNN

device='cuda' if torch.cuda.is_available() else 'cpu'
mtcnn=MTCNN(keep_all=True,device=device)
test_df=pd.read_csv('./input/data/eval/info.csv')
path='./input/data/eval/images'
new_path='./input/data/eval/new_images'
if not os.path.exists(new_path):
    os.mkdir(new_path)
for i in test_df.values:
    img=cv2.imread(os.path.join(path,i[0]))
    img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    boxes,probs= mtcnn.detect(img)
    if not isinstance(boxes,np.ndarray):
        print('oh no')
        img=img[100:400,50:350,:]
    else:
        xmin=int(boxes[0,0])-20
        ymin=int(boxes[0,1])-30
        xmax=int(boxes[0,2])+20
        ymax=int(boxes[0,3])+30
        if xmin<0:xmin=0
        if ymin<0:ymin=0
        if xmax>384:xmax=384
        if ymax>512:ymax=512
        img=img[ymin:ymax,xmin:xmax,:]
    plt.imsave(os.path.join(new_path,i[0]),img)